POST http://localhost:3000/posts
Content-Type: application/json
{    
    "title": "Nest JS starter",
    "postType": "post",
    "content": "Test content",
    "img": "http://www.imgurl.example.in",
    "tags": [5]
}